### ISSUE TITLE
URL redirection is corrupted

### ISSUE THREAD

**Issue by sontqq** [connornishijima/AlertMe#4] opened 2018-08-13 14:11 UTC
Everytime I connect to the AP it redirects me to `http://smtp.gmail.com192.168.4.1/`.
Even if I try to enter the IP manually.

Debug lines:
```
*ALERTME: Mounting SPIFFS...
*ALERTME: Mounted file system.
*ALERTME: Reading alertme_config.json...
*ALERTME: Opened config file!
*ALERTME: Parsed config:
{"smtp_server":"smtp.gmail.com","smtp_port":465,"smtp_email":"****","smtp_password":"****"}*ALERTME: 

*ALERTME: Connecting to your WiFi network...

Failed to connect to WiFi, config AP active at: 'AlertMe Configuration'
```

Any idea how to resolve it?

**Comment by petri1973** [comment] 2019-03-02 12:21
Hi.

I have the same problem, please fix it.

**Comment by petri1973** [comment] 2019-03-03 07:24
Ok, found the reason, its not compatible with the esp8266 2.5.0, 2.4.2 and it works!

Thanks!!

**Comment by mikekgr** [comment] 2019-03-03 07:37
Hello @petri1973 did you try the latest GitHub version ( master ) of ESP8266 Arduino core? I encourage you to try it as they have done many corrections. In this case, please report here if it working or not!

**Comment by petri1973** [comment] 2019-03-03 09:10
Hi mikekgr,

Yes, the problem is with the latest version, when installed 2.4.2 the corruption of json stopped.
Allthough, if the field in web interface is left empty once, and then try to update it, corrupted again..

**Comment by mikekgr** [comment] 2019-03-03 11:04
Hello again @petri1973 ,
please make sure that you have installed the latest GitHub version, master that is cocked now and not the released 2.5.0 that have some problems...
If you indeed have the master installed and still have the problem, then it is important to file an issue to them...
Best Regards,
Mike Kranidis

**Comment by petri1973** [comment] 2019-03-04 04:46
Hi mikekgr,

Yes, I used the direct link to pull the branch with the GitHub desktop app.
Also tried the zip. And added the cjson link to arduino 1.8.8. (stable release), and from boards manager installed the latest version.

So tried all possible ways that I know of. Quite new with this stuff, but had no similar issues before with other projects.

After installed the 2.4.2 the problem went away, now the code is working.

**Comment by drinnird** [comment] 2019-07-30 07:01
Is there a fix for this? I have tried all the versions since 2.4.2 and cannot get this to work except with 2.4.2. only issue is corruption after web interface is left empty.

**Comment by drderiv** [comment] 2019-08-26 03:46
I've proposed a fix for this that prevents the issue from happening regardless of the version of esp8266. It may have worked in previous versions due to the way the older kernel allocates memory, but regardless there was indeed a bug in the code which I've created a PR for.

**Comment by connornishijima** [comment] 2019-12-15 01:28
drderiv's fix was merged just now. Sorry for the wait!

**Closed by connornishijima** 2019-12-15 01:28 UTC

**Comment by zacharymelo** [comment] 2020-02-29 05:59
I see this issue is marked fixed, and I can see the fix - what I can't see is how it's related to the symptom I am seeing:

The string smtp.gmail.com is appearing in different places within the page, as if being loaded from somewhere it shouldn't. This includes behaviour the same as the original issue, wherein the URL becomes malformed.
